<a href="https://colab.research.google.com/github/TANKIANAUN/ML-learning/blob/master/machine_learning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
e=2.1718281828
answer=42
message='Hello World'

In [0]:
import numpy as np
a=np.array([1,2,3,4,5])
a[::4]
a

array([1, 2, 3, 4, 5])

In [0]:
print('%.10f'%e)
print('%d'%answer)
print('%s'%message)

2.1718281828
42
Hello World


In [0]:
print('{}'.format(e))
print('{}'.format(answer))
print('{}'.format(message))

2.1718281828
42
Hello World


In [0]:
vector_a=[1,2]
vector_b=[2,2]

In [0]:
sum=0
for i in range(len(vector_a)):
  sum=sum+vector_a[i]*vector_b[i]


In [0]:
x=np.array([1,2,3,4,5,6,7,8,9])

In [0]:
x1=x.reshape(len(x),1)

In [0]:
print(x1)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]


In [0]:
print('dot product = %.2f'%sum)

dot product = 6.00


In [0]:
b11=np.array([[1],[2]])
b11

In [0]:
(a11,b22)=b11

In [0]:
a11


array([1])

In [0]:
b22

array([2])